#!/usr/bin/env bash

VAGRANT_SHARED=/vagrant
SECRET_KEYS_DIR=$VAGRANT_SHARED/secret_keys
PUB_KEYS_DIR=$VAGRANT_SHARED/pub_keys
PROVISION_SCRIPTS=$VAGRANT_SHARED/provision_scripts
CI_SCRIPTS=$VAGRANT_SHARED/ci_scripts

RUBIES="2.0.0 1.9.3"
DEFAULT_RUBY="2.0.0"
